name: Maven Package
on:
  workflow_dispatch:
  push:
jobs:
  GuicedInjection:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: ''
      name: 'Guiced Vert.x Injection'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}